# Generated by Django 5.1.1 on 2024-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postcomment_postlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='watching',
            field=models.BigIntegerField(default=0),
        ),
    ]
