# Generated by Django 5.1.1 on 2024-11-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default/logo.png', max_length=250, null=True, upload_to='avatars/', verbose_name='avatar'),
        ),
    ]
